server:
  port: 18081
spring:
  application:
    name: my-manus

agent-model:
  base-url: https://ark.cn-beijing.volces.com/api
  api-key: {MY_API_KEY}
  model-name: deepseek-v4-pro-260425
  completions-path: /v3/chat/completions
  stream: false
plan-model:
  base-url: https://ark.cn-beijing.volces.com/api
  api-key: {MY_API_KEY}
  model-name: deepseek-v4-pro-260425
  completions-path: /v3/chat/completions

file:
  base: F:\\tmp\\my-manus\\
  domain: http://localhost:18081
